### ISSUE TITLE
All bars of bar plot are black

### ISSUE THREAD

**Issue by DMAgit** [sollan/apa.mplstyle#1]
Seems like for bar plots all of the bars are black. I don't know how one could fix this, unfortunately.

Here's an example:
![hist_y_unbalanced](https://user-images.githubusercontent.com/44362174/122206259-d39cde00-cea9-11eb-9e9d-c8bdc4053bff.png)

Produced by the following code:

```
import matplotlib.pyplot as plt 
import matplotlib
matplotlib.style.use('apa.mplstyle') # selecting the style sheet

plt.bar(x=["Class B", "Classes > B"], height=[(y_train["B"] == 1).sum(), (y_train["B"] == 0).sum()])
```

**Comment by sollan** [comment]
Hi! Sorry for the late reply. I managed to reproduce your result :) (Next time please provide a generic example - one that doesn't involve a specific dataset)

Unfortunately you can't plot multiple classes with a single line of code (I think) while using the cycler that goes through the aesthetic properties... 

So if you could plot each group by calling ```plt.bar()``` separately, that should work. Like this: 

```
plt.bar(x='B', height=10)
plt.bar(x='> B', height=20)
```
![image](https://user-images.githubusercontent.com/16420946/123235463-2dba2680-d4dc-11eb-89f2-04dd95d9e96e.png)

And if you would like to add hatches, they would need to be specified manually. 

```
plt.bar(x='B', height=10)
plt.bar(x='> B', height=20, hatch='/')
```

![image](https://user-images.githubusercontent.com/16420946/123235812-812c7480-d4dc-11eb-8b01-a11efda3b5ed.png)

**Comment by sollan** [comment]
Update:

Sorry, one more thing. Turns out I also forgot to update the Github version, so the old version uses 'k' (black) as the first two colors to loop through in the color cycler. I've since fixed it. Please check the latest version. 

Hope that helps!
